#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ${ssh_key}
write_files:
  - content: |
      config setup
      conn azure-conn
        auto=start
        left=%defaultroute
        leftid=${left_id}
        right=${right}
        type=tunnel
        leftauth=psk
        rightauth=psk
        keyexchange=ikev2
        ike=aes128-sha256-modp2048
        ikelifetime=8h
        esp=aes128-sha256-modp2048
        lifetime=1h
        keyingtries=%forever
        leftsubnet=${leftsubnet}
        rightsubnet=${rightsubnet}
        dpddelay=10s
        dpdtimeout=30s
        dpdaction=restart
    path: /etc/ipsec.conf
    permissions: '0644'
  - content: |
      ${left_id} ${right} : PSK "${psk}"
    path: /etc/ipsec.secrets
    permissions: '0600'
runcmd:
  - sleep 30
  - reboot
